apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: basedepartments.yamecloud.io
spec:
  group: yamecloud.io
  names:
    kind: BaseDepartment
    listKind: BaseDepartmentList
    plural: basedepartments
    singular: basedepartment
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: BaseDepartment is the Schema for the basedepartments API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/action-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/action-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BaseDepartmentSpec defines the desired state of BaseDepartment
            properties:
              tenant_id:
                type: string
              defaultNamespace:
                type: string
              gits:
                items:
                  properties:
                    address:
                      type: string
                    password:
                      type: string
                    token:
                      type: string
                    user:
                      type: string
                    verification:
                      type: string
                  type: object
                type: array
              namespace:
                items:
                  type: string
                type: array
              registers:
                items:
                  properties:
                    address:
                      type: string
                    password:
                      type: string
                    token:
                      type: string
                    user:
                      type: string
                    verification:
                      type: string
                  type: object
                type: array
            type: object
          status:
            description: BaseDepartmentStatus defines the observed state of BaseDepartment
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
