apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: basetenants.yamecloud.io
spec:
  group: yamecloud.io
  names:
    kind: BaseTeant
    listKind: BaseTeantList
    plural: basetenants
    singular: basetenant
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: BaseTeant is the Schema for baseteants API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/action-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/action-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BaseTeantSpec defines the desired state of BaseTeant
            properties:
              name:
                type: string
              departments:
                items:
                  type: string
                type: array
            type: object
          status:
            description: BaseTeantStatus defines the observed state of BaseTeant
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
